spring:
  application:
    name: server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/ticdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1997
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        schema_update: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  logging:
    level: 
      ROOT: INFO